//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSSLTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QSSLTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already expired.
        /// </summary>
        public static string alreadyExpired {
            get {
                return ResourceManager.GetString("alreadyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already expired ({0}).
        /// </summary>
        public static string alreadyExpiredCount {
            get {
                return ResourceManager.GetString("alreadyExpiredCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer Settings.
        /// </summary>
        public static string analyzerSettings {
            get {
                return ResourceManager.GetString("analyzerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enter settings while an analysis is happening..
        /// </summary>
        public static string cannotEnterSettings {
            get {
                return ResourceManager.GetString("cannotEnterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to API (ssllabs.com).
        /// </summary>
        public static string connectedToAPI {
            get {
                return ResourceManager.GetString("connectedToAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open file. Is another process accessing it?.
        /// </summary>
        public static string couldntOpenFile {
            get {
                return ResourceManager.GetString("couldntOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days for warning Expiration.
        /// </summary>
        public static string daysForWarning {
            get {
                return ResourceManager.GetString("daysForWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time: {0} / {1}.
        /// </summary>
        public static string elapsedTime {
            get {
                return ResourceManager.GetString("elapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        public static string errorsOccurred {
            get {
                return ResourceManager.GetString("errorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration filter.
        /// </summary>
        public static string expirationFilter {
            get {
                return ResourceManager.GetString("expirationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        public static string exportSettings {
            get {
                return ResourceManager.GetString("exportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} hosts analyzed.
        /// </summary>
        public static string hostsAnalyzed {
            get {
                return ResourceManager.GetString("hostsAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore certificate name mismatch.
        /// </summary>
        public static string ignoreMismatch {
            get {
                return ResourceManager.GetString("ignoreMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative color (background).
        /// </summary>
        public static string negativeColorBackground {
            get {
                return ResourceManager.GetString("negativeColorBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative color (foreground).
        /// </summary>
        public static string negativeColorForeground {
            get {
                return ResourceManager.GetString("negativeColorForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative sample.
        /// </summary>
        public static string negativeSample {
            get {
                return ResourceManager.GetString("negativeSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral color (background).
        /// </summary>
        public static string neutralColorBackground {
            get {
                return ResourceManager.GetString("neutralColorBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral color (foreground).
        /// </summary>
        public static string neutralColorForeground {
            get {
                return ResourceManager.GetString("neutralColorForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral sample.
        /// </summary>
        public static string neutralSample {
            get {
                return ResourceManager.GetString("neutralSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to API (ssllabs.com).
        /// </summary>
        public static string notConnectedToAPI {
            get {
                return ResourceManager.GetString("notConnectedToAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive color (background).
        /// </summary>
        public static string positiveColorBackground {
            get {
                return ResourceManager.GetString("positiveColorBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive color (foreground).
        /// </summary>
        public static string positiveColorForeground {
            get {
                return ResourceManager.GetString("positiveColorForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive sample.
        /// </summary>
        public static string positiveSample {
            get {
                return ResourceManager.GetString("positiveSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish results.
        /// </summary>
        public static string publishResults {
            get {
                return ResourceManager.GetString("publishResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Everything ({0}).
        /// </summary>
        public static string rankingEverything {
            get {
                return ResourceManager.GetString("rankingEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking filter.
        /// </summary>
        public static string rankingFilter {
            get {
                return ResourceManager.GetString("rankingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only As ({0}).
        /// </summary>
        public static string rankingOnlyAs {
            get {
                return ResourceManager.GetString("rankingOnlyAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Bs ({0}).
        /// </summary>
        public static string rankingOnlyBs {
            get {
                return ResourceManager.GetString("rankingOnlyBs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Cs ({0}).
        /// </summary>
        public static string rankingOnlyCs {
            get {
                return ResourceManager.GetString("rankingOnlyCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower than Cs ({0}).
        /// </summary>
        public static string rankingOnlyLower {
            get {
                return ResourceManager.GetString("rankingOnlyLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent outcome for {0}.
        /// </summary>
        public static string recentOutcome {
            get {
                return ResourceManager.GetString("recentOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single host analysis.
        /// </summary>
        public static string singleAnalysis {
            get {
                return ResourceManager.GetString("singleAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL has to be a proper HTTPS address..
        /// </summary>
        public static string urlMustBeHttps {
            get {
                return ResourceManager.GetString("urlMustBeHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use cached results.
        /// </summary>
        public static string useCachedResults {
            get {
                return ResourceManager.GetString("useCachedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warned expirations.
        /// </summary>
        public static string warnedExpirations {
            get {
                return ResourceManager.GetString("warnedExpirations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warned expirations ({0}).
        /// </summary>
        public static string warnedExpiredCount {
            get {
                return ResourceManager.GetString("warnedExpiredCount", resourceCulture);
            }
        }
    }
}
